import React from "react";
import { motion } from "framer-motion";
import LightServiceNavigation from "@/components/navigation/LightServiceNavigation";
import { SigninGradientBackground } from "@/components/ui/signin-gradient-background";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const RefundPolicy: React.FC = () => {
  return (
    <SigninGradientBackground>
      <div className="min-h-screen flex">
        <LightServiceNavigation />

        <main className="flex-1 ml-0 lg:ml-64 px-4 py-8">
          <div className="max-w-4xl mx-auto">
            {/* Back Button */}
            <Link
              to="/dashboard"
              className="inline-flex items-center gap-2 text-white/70 hover:text-white mb-8 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Dashboard
            </Link>

            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="mb-12"
            >
              <h1 className="text-5xl md:text-6xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-400 mb-6">
                Refund and Cancellation Policy
              </h1>
            </motion.div>

            {/* Content */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="space-y-6"
            >
              <div className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10 space-y-6">
                <div>
                  <h2 className="text-2xl font-bold text-white mb-4">
                    Our Policy on Refunds
                  </h2>
                  <p className="text-white/80 leading-relaxed">
                    Calmira AI provides digital, AI-generated services that are
                    personalized and rendered instantly. Due to the
                    computational costs and immediate delivery of our services
                    (such as Manga Generation and DhyaanAI Meditation sessions),
                    we generally do not offer refunds or cancellations once a
                    service has been successfully generated and delivered.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-white mb-4">
                    Refund Scenarios
                  </h2>

                  <div className="space-y-4">
                    <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                      <h3 className="text-xl font-semibold text-white mb-2">
                        Technical Failure
                      </h3>
                      <p className="text-white/80 leading-relaxed">
                        If you are charged for a service but it fails to
                        generate due to a technical error on our platform (e.g.,
                        the manga story is not created, the meditation audio is
                        not produced), please contact our support team at{" "}
                        <a
                          href="mailto:rohitworks.ai@gmail.com"
                          className="text-purple-400 hover:text-purple-300"
                        >
                          rohitworks.ai@gmail.com
                        </a>{" "}
                        within 48 hours. We will investigate the issue and, at
                        our discretion, either provide a credit for the service
                        or issue a full refund to your original payment method.
                      </p>
                    </div>

                    <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                      <h3 className="text-xl font-semibold text-white mb-2">
                        Subjective Dissatisfaction
                      </h3>
                      <p className="text-white/80 leading-relaxed">
                        Our services are generated by complex AI. While we
                        strive for high quality, we cannot guarantee subjective
                        satisfaction with the creative output (e.g., you do not
                        like the art style of the manga or the voice of the
                        meditation guide). Refunds will not be issued for
                        reasons of personal taste or subjective dissatisfaction.
                      </p>
                    </div>

                    <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                      <h3 className="text-xl font-semibold text-white mb-2">
                        Duplicate Charges
                      </h3>
                      <p className="text-white/80 leading-relaxed">
                        In the event of an accidental duplicate charge, please
                        contact us immediately with the transaction details. We
                        will verify the duplicate charge and refund it in full.
                      </p>
                    </div>

                    <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                      <h3 className="text-xl font-semibold text-white mb-2">
                        Processing Time
                      </h3>
                      <p className="text-white/80 leading-relaxed">
                        Approved refunds will be processed within 7-10 business
                        days.
                      </p>
                    </div>

                    <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                      <h3 className="text-xl font-semibold text-white mb-2">
                        Returns & Exchanges
                      </h3>
                      <p className="text-white/80 leading-relaxed">
                        As our products are intangible digital services, returns
                        and exchanges are not applicable.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </main>
      </div>
    </SigninGradientBackground>
  );
};

export default RefundPolicy;
