import React from "react";
import { motion } from "framer-motion";
import LightServiceNavigation from "@/components/navigation/LightServiceNavigation";
import { SigninGradientBackground } from "@/components/ui/signin-gradient-background";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const TermsAndConditions: React.FC = () => {
  return (
    <SigninGradientBackground>
      <div className="min-h-screen flex">
        <LightServiceNavigation />

        <main className="flex-1 ml-0 lg:ml-64 px-4 py-8">
          <div className="max-w-4xl mx-auto">
            {/* Back Button */}
            <Link
              to="/dashboard"
              className="inline-flex items-center gap-2 text-white/70 hover:text-white mb-8 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Dashboard
            </Link>

            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="mb-12"
            >
              <h1 className="text-5xl md:text-6xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-400 mb-6">
                Terms and Conditions
              </h1>
              <p className="text-white/80 text-lg">
                Welcome to Calmira.ai. By using our website and services, you
                agree to the following terms and conditions:
              </p>
            </motion.div>

            {/* Content */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="space-y-6"
            >
              <div className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10 space-y-6">
                <div className="space-y-4">
                  <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                    <h3 className="text-xl font-semibold text-white mb-3">
                      Service Provision
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      Our services (AI Manga, Voice Chat, DhyaanAI) are provided
                      on an "as-is" basis. They are generated by artificial
                      intelligence based on your inputs.
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                    <h3 className="text-xl font-semibold text-white mb-3">
                      User Inputs
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      You grant Calmira AI a non-exclusive, worldwide,
                      royalty-free license to use the inputs you provide (e.g.,
                      mood, challenges) solely for the purpose of generating
                      your personalized content and improving our service. We
                      will not share your personal inputs with third-party
                      marketers.
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                    <h3 className="text-xl font-semibold text-white mb-3">
                      Digital Delivery
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      All services are delivered digitally to your user account
                      on our platform. You acknowledge that no physical goods
                      will be shipped.
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                    <h3 className="text-xl font-semibold text-white mb-3">
                      Customer Support
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      For any issues or queries regarding our services, please
                      contact our customer support team at{" "}
                      <a
                        href="mailto:rohitworks.ai@gmail.com"
                        className="text-purple-400 hover:text-purple-300"
                      >
                        rohitworks.ai@gmail.com
                      </a>
                      . We aim to respond to all queries within 2 business days.
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                    <h3 className="text-xl font-semibold text-white mb-3">
                      Dispute Resolution
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      Any dispute arising out of your use of our services will
                      be governed by the laws of India and subject to the
                      exclusive jurisdiction of the courts in Bengaluru,
                      Karnataka.
                    </p>
                  </div>

                  <div className="bg-white/5 rounded-xl p-6 border border-white/10">
                    <h3 className="text-xl font-semibold text-white mb-3">
                      Compliance
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      You agree to use our services in compliance with all
                      applicable local, state, national, and international laws.
                      You agree not to use the service to generate content that
                      is hateful, harassing, or illegal.
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </main>
      </div>
    </SigninGradientBackground>
  );
};

export default TermsAndConditions;
